version: '3.4'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" 
    networks:
      - BTO
    develop:
      watch:
        - action: sync+restart
          path: ./frontend
          target: /app
          ignore:
            - node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  
    networks:
      - BTO
    
networks:
  BTO: